#!/bin/bash

if [ "$1" == "" ]; then
	echo
	echo "Usage: deploy [stage|prod] [test]"
	echo
	exit 1
fi

server = 'heroku'

if [ "$2" == "test" ]; then
	TEST_COMMAND="echo Not Running: python manage.py test"
	PUSH_COMMAND="echo Not Running: git push $server master"
	POST_TEST="echo Not Running: scripts/post_deploy_test heroku $1"
    MIGRATE_COMMAND="echo Not Running heroku run python manage.py migrate --app"
else
	TEST_COMMAND="python manage.py test"
	PUSH_COMMAND="git push $server master"
    MIGRATE_COMMAND="heroku run python manage.py migrate --app $server"
	POST_TEST="scripts/post_deploy_test heroku $1"
fi

echo "Running tests..."
cd ~/src/tp
source ~/env/tp3/bin/activate
echo Executing: $TEST_COMMAND
$TEST_COMMAND

if [ $? != 0 ]; then
	echo "TESTS FAILED."
	echo "Deployment HALTED."
	exit 1
fi

echo "Checking git status..."
git_status=`git status -s`
if [ "$git_status" != "" ]; then
	echo "Git not up to date"
	echo "------------------------"
	echo "$git_status"
	echo "------------------------"
	echo "Exiting."
	exit 1
fi
git_branch_status=`git status -sb`
if [ "$git_branch_status" != "## master...origin/master" ]; then
	echo "Origin Master is not up to date"
	echo "------------------------"
       	echo "$git_branch_status"
	echo "------------------------"
	echo "Exiting."
	exit 1
fi

echo "Pushing code to *** $server ***"
echo "------------------------------------"
echo Executing: $PUSH_COMMAND
$PUSH_COMMAND
if [ $? -ne 0 ]; then
	echo "Deployment FAILED"
	exit 1
fi

echo "Running migrate"
$MIGRATE_COMMAND

echo "Deployment SUCCESSFUL"
echo "sleep 60 to wait for server to be back up"
sleep 60
echo "Running tests now with: $POST_TEST"
$POST_TEST
